Add unit tests for cc.dodder.common.util.ByteUtil
Diffblue-benchmarks/Dodder pull request #3
Opened 2019-05-22 16:24 UTC by ThomasPerkins1123

Hi,

I've analysed your code base and noticed that `cc.dodder.common.util.ByteUtil` in the `dodder-common` module is not fully tested.

I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

2019-05-22 16:55 UTC, freddytuxworth requested changes

2019-05-22 16:55 UTC, freddytuxworth commented on dodder-common/src/test/java/cc/dodder/common/util/ByteUtilTest.java
> +        assertArrayEquals(new byte[]{ (byte)62 },
remove explicit `(byte)` cast

2019-05-22 16:55 UTC, freddytuxworth commented on dodder-common/src/test/java/cc/dodder/common/util/ByteUtilTest.java
> +                { (byte)0, (byte)0, (byte)0, (byte)0, (byte)1, (byte)1 }));
remove all `(byte)` (not needed for -128<x<127)

2019-05-22 16:55 UTC, freddytuxworth commented on dodder-common/src/test/java/cc/dodder/common/util/ByteUtilTest.java
> +        assertArrayEquals(new byte[]{(byte)0, (byte)0, (byte)0, (byte)0},
remove all `(byte)` (not needed for -128<x<127)

2019-05-22 16:55 UTC, freddytuxworth commented on dodder-common/src/test/java/cc/dodder/common/util/ByteUtilTest.java
> +                new byte[]{ (byte)62 }, true));
remove all `(byte)` (not needed for -128<x<127)

2019-05-22 16:55 UTC, freddytuxworth commented on dodder-common/src/test/java/cc/dodder/common/util/ByteUtilTest.java
> +        assertNull(ByteUtil.byteArrayToHex(new byte[] { }, false));
replace `new byte[] { }` with `new byte[0]`

2019-05-22 16:55 UTC, freddytuxworth commented on dodder-common/src/test/java/cc/dodder/common/util/ByteUtilTest.java
> +                ByteUtil.intToByteArray(0));
Add a test for an int >0

2019-05-22 16:55 UTC, freddytuxworth commented on dodder-common/src/test/java/cc/dodder/common/util/ByteUtilTest.java
> +                { (byte)0, (byte)0, (byte)0, (byte)0, (byte)1, (byte)1 }));
add a test which gives an int other than 0

2019-05-23 09:26 UTC, freddytuxworth approved these changes

2019-06-03 07:53 UTC, paulkennethkent approved these changes

2019-09-04 13:10 UTC, closed without merging